spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bank
    username: postgres
    password: 69haslo69!
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  security:
    filter:
      dispatcher-types: REQUEST, ERROR

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # 86400000 # a day
      refresh-token:
        expiration: 259200000 # 7 days
